on: push
name: 🚀 Deploy website on push

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest

    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2

      - name: 📂 Sync files to /staloysius
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: 70.32.23.41
          username: ${{ secrets.ftp_username }}
          password: ${{ secrets.ftp_password }}
          server-dir: /staloysius/
          exclude: |
            **/.git*
            **/node_modules/**
            **/vendor/**
            storage/**
            .env
